name: covid19app
description: A new Flutter application.

version: 1.2.1+1006

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  hasura_connect: ^1.2.1+1
  dio_http_cache: ^0.2.6
  shared_preferences: ^0.5.6+3
  dio: ^3.0.9
  mobx: ^1.1.1
  flutter_modular: ^1.0.0
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.7.0
  flutter_mobx: ^1.1.0
  transparent_image: ^1.0.0
  date_format: ^1.0.8
  mask_text_input_formatter: ^1.0.6
  intl: ^0.16.1
  http: ^0.12.0+4
  location: ^3.0.2
  #  hive: ^1.4.1+1
  #  hive_flutter: ^0.3.0+2
  responsive_screen: ^1.0.0
  flutter_launcher_icons: ^0.7.4
  # firebase_messaging: ^6.0.13
  fl_chart: ^0.9.0
  url_launcher: ^5.4.11
  webview_flutter: ^0.3.22+1
  firebase_messaging: ^6.0.16

  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^4.1.1
  mobx_codegen: ^1.0.3
  build_runner: ^1.8.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo-pmst.png
    - assets/images/logo-pmst-1.png
    - assets/images/logo-pmst-2.png
    - assets/images/logobsi.png
    - images/background.png
    - assets/images/logouast.png
    - assets/images/analys.png
    - assets/images/covid.png
    - assets/icons/analys_icon.png
    - assets/icons/feed_icon.png
    - assets/icons/covid_contact.png
    - assets/icons/sintomas.png
    - assets/icons/fever.png
    - assets/icons/info.png
    - assets/icons/news_icon.png
    - assets/icons/boletim_icon.png
    - assets/icons/tips_icon.png
    - assets/icons/analise.png
    - assets/icons/sobre_black.png
    - assets/images/header.png
    - assets/images/health_center.png
    - assets/images/capa.png
    - assets/images/logo.png
    - assets/icons/lungs.png
    - assets/icons/house.png
    - assets/icons/distance.png
    - assets/icons/placeholder.png
    - assets/icons/temperature.png
    - assets/icons/symptom.png
    - assets/icons/icon.png
    - assets/icons/dashboard_icon.png
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: - assets/icons/covid.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
scripts: 

  mobx_watch: flutter pub run build_runner watch 

  mobx_build: flutter clean & flutter pub get & flutter pub run build_runner build --delete-conflicting-outputs
